Update reusable-create-shared-issue.yml

diff --git a/.github/workflows/reusable-create-shared-issue.yml b/.github/workflows/reusable-create-shared-issue.yml
--- a/.github/workflows/reusable-create-shared-issue.yml
+++ b/.github/workflows/reusable-create-shared-issue.yml
@@ -52,21 +52,26 @@ jobs:
           
               project_name="$(date +'%B %Y') Sprint"
               echo "Locating project '$project_name' in $PROJECT_ORG..."
-              project_json=$(gh projects list --owner "$PROJECT_ORG" --format json 2>/dev/null)
-              echo "$project_json"
-              if ! echo "$project_json" | jq empty; then
-                echo "Failed to get valid JSON from gh projects list"
-                echo "$project_json"
-                exit 1
-              fi
-              project_id=$(echo "$project_json" | jq -r --arg name "$project_name" '.[] | select(.title == $name) | .id')
+              #project_json=$(gh projects list --owner "$PROJECT_ORG" --format json 2>/dev/null)
+              #echo "$project_json"
+              #if ! echo "$project_json" | jq empty; then
+              #  echo "Failed to get valid JSON from gh projects list"
+              #  echo "$project_json"
+              #  exit 1
+              #fi
+              #project_id=$(echo "$project_json" | jq -r --arg name "$project_name" '.[] | select(.title == $name) | .id')
           
-              if [[ -n "$project_id" ]]; then
-                echo "Adding issue to project"
-                gh projects item-create --project-id "$project_id" --url "$issue_url"
-              else
-                echo "Project '$project_name' not found in $PROJECT_ORG"
-              fi
+              #if [[ -n "$project_id" ]]; then
+              #  echo "Adding issue to project"
+              #  gh projects item-create --project-id "$project_id" --url "$issue_url"
+              #else
+              #  echo "Project '$project_name' not found in $PROJECT_ORG"
+              #fi
+              echo "Try listing projects for: $PROJECT_ORG"
+              gh projects list --owner "$PROJECT_ORG" --format json
+
+              echo "Try listing classic projects:"
+              gh api orgs/$PROJECT_ORG/projects --paginate
             else
               echo "Issue already exists in $repo"
             fi
